version: '3.4'
services:
    ticketing.api:
        image: '${DOCKER_REGISTRY-}ticketingapi'
        build:
            context: .
            dockerfile: Ticketing.Api/Dockerfile
        depends_on:
            - db
    db:
        image: mcr.microsoft.com/mssql/server
        environment:
            SA_PASSWORD: "Password123"
            ACCEPT_EULA: "Y"
        volumes:
            - ./Migrations/scripts:/scripts/
            - ./Migrations/data:/var/opt/mssql/data
        ports:
            - '1433:1433'
        command:
            - /bin/bash
            - -c
            - |
              # Launch MSSQL and send to background
              /opt/mssql/bin/sqlservr &
              # Wait 30 seconds for it to be available
              sleep 30
              # Run every script in /scripts
              for script in /scripts/*.sql
                do /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -l 30 -e -i script
              done
              # So that the container doesn't shut down, sleep this thread
              sleep infinity